### ISSUE TITLE
Error setting up entry Windcentrale for windcentrale

### ISSUE THREAD

**Issue by Xorfor** [jobvk/Home-Assistant-Windcentrale#113]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

I just installed the beta version, but got:

Logger: homeassistant.config_entries
Source: custom_components/windcentrale/wind.py:26
Integration: Windcentrale ([documentation](https://github.com/jobvk/Home-Assistant-Windcentrale), [issues](https://github.com/jobvk/Home-Assistant-Windcentrale/issues))
First occurred: 22:31:05 (1 occurrences)
Last logged: 22:31:05

Error setting up entry Windcentrale for windcentrale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/windcentrale/__init__.py", line 19, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id] = wind.Wind(hass, entry)
  File "/config/custom_components/windcentrale/wind.py", line 26, in __init__
    self.credentialsapi = Credentials(self.hass, self.config_entry.data[CONF_EMAIL], self.config_entry.data[CONF_PASSWORD], self.config_entry.data[CONF_PLATFORM])
KeyError: 'platform'

### What is version of Home Assistant Core did you recieve the bug?

2023.5.4

### What is version of Home Assistant Supervisor did you recieve the bug?

2023.04.1

### What is version of Home Assistant Supervisor?

2023.04.1

### What is version of the Windcentrale integration?

0.2.7-Beta

### Additional information

It looks like it is related to the latest changes in platform webhook. For an other configuration, I needed to add '      allowed_methods:
        - POST
'.

**Comment by jobvk** [comment]
Yeah it's a beta. For people using https://winddelen.nl/ look at https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/95.

For you, reinstall the component it should still work or just go back to [0.2.6](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.2.6)

**Comment by Xorfor** [comment]
I did a reinstall and everythings works again. I will ignore the beta versions in the future!
