### ISSUE TITLE
 No resulta from my Mills.

### ISSUE THREAD

**Issue by BenSpruyt** [jobvk/Home-Assistant-Windcentrale#132]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

No resulta from my Mills (de trouwe wachter en de grote geert) for more thee 3 days.

### What is version of Home Assistant Core did you recieve the bug?

Latest

### What is version of Home Assistant Supervisor did you recieve the bug?

Latest

### What is version of Home Assistant Supervisor?

Latest

### What is version of the Windcentrale integration?

0.2.7

**Comment by jobvk** [comment]
In this case, all windmills maybe have these problems.
It seems that the timestamp of the live data of all wind turbines has not been updated since:

Saturday, 5 August 2023 10:02:25 [GMT+02:00](https://en.wikipedia.org/wiki/UTC%2B02:00) DST

All the live sensors look like they are also not updating, but they are switching between 2 values.

![image](https://github.com/jobvk/Home-Assistant-Windcentrale/assets/32730202/5c06cf4b-28a6-4df3-92d4-323819a4bb5c)

There is nothing I can do myself. But please contact [The Windcentrale Company](https://www.windcentrale.nl/contact). They should fix the Live API, History API works fine.

**Comment by Xorfor** [comment]
Let us all contact the Windcentrale Company together!

Since the Windcentrale switched to a different provider for the data, the problems with the data have only gotten worse. 

It is time consuming to explain Windcentrale the problem (fortunately the 'Live productie' page has the same problem), but maybe then they will take this problem more seriously.

**Comment by jobvk** [comment]
There doesn't really seem to be an improvement yet.

**Comment by Frank071** [comment]
Only found this integration yesterday :-( and immediately stumbled upon this problem. The Windcentrale site has a 'live production' page that seems live, but only if you check it more than once you notice that the figures do not change... So this really is a problem with them - no need to mark it as a 'bug'... I filed a support ticket with them, let's see what happens (based on earlier experience, I don't hold my breath)

**Comment by BenSpruyt** [comment]
Beste …,

 

Ik heb reeds op 13 augustus het probleem aangemeld bij de Windcentrale.

 

En ook nog niets gehoord!

 

Bijgaand het betreffende mailtje.

 

Mvg,

 

Ben Spruyt

 

Van: Frank Maas ***@***.*** 
Verzonden: maandag 28 augustus 2023 09:01
Aan: jobvk/Home-Assistant-Windcentrale
CC: BenSpruyt; Author
Onderwerp: Re: [jobvk/Home-Assistant-Windcentrale] No resulta from my Mills. (Issue #132)

 

Only found this integration yesterday :-( and immediately stumbled upon this problem. The Windcentrale site has a 'live production' page that seems live, but only if you check it more than once you notice that the figures do not change... So this really is a problem with them - no need to mark it as a 'bug'... I filed a support ticket with them, let's see what happens (based on earlier experience, I don't hold my breath)

**Comment by sebastianberm** [comment]
Ik heb tickets geopend voor elke molen waar ik een winddeel heb. Kortom, hebben ze hier net 5 tickets over gekregen met screenshots en berekeningen erbij.

**Comment by Frank071** [comment]
Antwoord van "Sanne": _Het klopt inderdaad dat bij sommige klanten de live productie niet werkt. Er is hier momenteel een storing in. Dit loopt bij onze IT-dienst op het moment. Zodra dit probleem opgelost is kunt u de live productie weer inzien._

**Comment by krispijnb** [comment]
I've contacted the Windcentrale 8 days ago. I've got a confirmation today that it has been reported to their IT department. They don't have a solution yet. To be continued I suppose.

**Comment by krispijnb** [comment]
I've got data for all windturbines coming in between 14 and 15hrs. Looks like it is data from several hours or days. Not sure if it means the api is up and running again.
<img width="803" alt="Schermafbeelding 2023-08-30 153936" src="https://github.com/jobvk/Home-Assistant-Windcentrale/assets/114363866/b1023828-bf01-4a49-b61a-aade5780555c">

**Comment by mschut** [comment]
I've got the same, unfortunately my rode hert is not working anymore (again). Sigh...

**Comment by ronaldvdvelden** [comment]
> I've got the same, unfortunately my rode hert is not working anymore (again). Sigh...

Same feeling here. Just send them a message to give an update on the repair. Also made a comment on the lack of communication by them. If the reply is unsatisfactory I am planning to make a formal complaint.

**Comment by Xorfor** [comment]
Finally, since 14:10 I receive data from my windmills and still working.

**Comment by Simanias** [comment]
Yes finally it is working again!
Hopefully they are more serious with the data providing this time.

**Comment by vressel** [comment]
vanochtend om 9h55 laatste sample van de Blauwe Reiger, het lijkt weer gestopt.

**Comment by Frank071** [comment]
Hmmm... ik weet niet wat daar bij de Windcentrale op zaterdagen om 10:00 gebeurt... (vorige uitval was 5 augustus om 10:02). Maar weer een ticket aanmaken dus.

**Comment by jobvk** [comment]
Looks like there is something happening.

Also, my last updated sensor switches between 2 september 10:02/10:04 and now

What I also want to say is how little they update the news. My latest one is from April 26 about regular maintenance. But nothing about the wrong data or that the API is not working.

**Comment by Xorfor** [comment]
Yes, I am getting some data for De Grote Geert and De Trouwe Wachter since 10:45. Still no information from the helpdesk.

**Comment by Frank071** [comment]
My status icon still says it updated 8 days ago, but the charts show some activity. They have a crappy (outsourced?) customer support, so no feedback whatsoever. It matches the level of their IT partner. But as said earlier: they don't seem to bother,  so we are stuck with it 
![IMG_20230909_232408](https://github.com/jobvk/Home-Assistant-Windcentrale/assets/807403/e14ad66e-002d-425f-82ff-1cd426a267bd)

**Comment by vressel** [comment]
The value of my mill is constantly swapping between the actual value (I hope) and the value of 2 September, it 's also visible in the app in the live-screen. There is some communication with the helpdesk by mail but that's not very helpful sofarl.

**Comment by vressel** [comment]
Since 13h32 this afternoon it seems alright again, no old values anymore.

**Comment by Xorfor** [comment]
@krispijnb Today I also received the same e-mail

**Comment by jobvk** [comment]
I'll close this issue for now. 

If, after the update on 01-10-2023, something breaks, such as the base_url, pool_id, or client_id, then a new issue will be created.


Thanks everyone for working together on this issue.
