### ISSUE TITLE
problem with loggin in with 0.1.4

### ISSUE THREAD

**Issue by mjrider** [jobvk/Home-Assistant-Windcentrale#17]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

I'm getting the following error while loggin in, and i cannot setup the integration.
```
2022-02-20 09:09:57 INFO (MainThread) [custom_components.windcentrale.wind] Colllecting windshares
2022-02-20 09:09:57 INFO (MainThread) [custom_components.windcentrale.wind] {'@id': '1', 'id': '31fb3523-5490-4ea........snipped personal info.........}
2022-02-20 09:09:57 ERROR (MainThread) [custom_components.windcentrale.config_flow] Unexpected exception when submitting windcentrale config
```

the snipped content contains the windcentrale items e.d. 

### What is version of Home Assistant Core did you recieve the bug?

core-2022.2.9

### What is version of Home Assistant Supervisor did you recieve the bug?

supervisor-2022.01.1

### What is version of Home Assistant Supervisor?

supervisor-2022.01.1

### What is version of the Windcentrale integration?

0.1.4

### Anything in the logs that might be useful for us?

i did try if it was a user/pass problem, and the process passes the stage where it collect the information from the windcentrale, i can see a full dump in the log of the windcentrale i have. It seems to break while processing those settings, and it aborts back to the config flow

**Comment by jobvk** [comment]
Hey @mjrider,

It looks like home assistant can't read the json file properly.
Could you send the whole json file, but replace all personal data with "private"
Then I can try to find where the problem is.

Thanks in advance

**Comment by mjrider** [comment]
hello, just checking, i cannot find a file of the type json with the content, if so, what would be the filename?
or did you need the full line i provider before, but with more information then i gave before

**Comment by jobvk** [comment]
@mjrider Your still having this problem?
