### ISSUE TITLE
Id in live url is sometimes different from the windmill id

### ISSUE THREAD

**Issue by blieven1** [jobvk/Home-Assistant-Windcentrale#22]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

I noticed I didn't get complete data for the Boerenzwaluw.

Apperently the id is 191 so the main url is : https://zep-api.windcentrale.nl/production/191
but the live url is https://zep-api.windcentrale.nl/production/201/live for some reason

https://zep-api.windcentrale.nl/production/201 looks like it gives the same data as https://zep-api.windcentrale.nl/production/191
so maybe it's just an update from 191 tot 201 as the id.

complete list: https://github.com/damonnk/windcentrale/blob/master/molens.xml

### What is version of Home Assistant Core did you recieve the bug?

2022.6.4

### What is version of Home Assistant Supervisor did you recieve the bug?

None

### What is version of Home Assistant Supervisor?

2022.6.4

### What is version of the Windcentrale integration?

1.4

**Comment by blieven1** [comment]
Verified with the data on https://mijnmolen.windcentrale.nl/#/

Boerenzwaluw should have 201 as the id

**Comment by jobvk** [comment]
I made a [beta release](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.1.5-Beta), please check if in this beta the problem still occurs.

You update to this beta through HACS

**Comment by blieven1** [comment]
Hi, It is working.

I also tried yesterday evening by just changing the id from 191 tot 201 in     https://github.com/jobvk/Home-Assistant-Windcentrale/blob/c3490e4352b80bd0cfc92b356b4df0df69415173/custom_components/windcentrale/const.py#L39

"De Boerenzwaluw": [201, "Enercon", "E-44", "Burum", 53.265376, 6.214152, dt.datetime(2016, 8, 1)],

Maybe that's a cleaner solution than having the if statement :)

Kind regards,
Bjorn

**Comment by jobvk** [comment]
Yes, it would be nicer.
But the problem is there are two API's working for production data:
- https://zep-api.windcentrale.nl/production/191
- https://zep-api.windcentrale.nl/production/201

And the problem is the data is a little bit different.

Also the news api uses the id of 191
![image](https://user-images.githubusercontent.com/32730202/173025839-32c7d1e1-1b51-4e19-86ea-46c88390e0fc.png)
So if i change the id of the windturbine to 201 the news filter doesn't work anymore

**Comment by blieven1** [comment]
Ok, thanx, didn't about the news feed.

Great work!
