### ISSUE TITLE
API Deprecated | No Data

### ISSUE THREAD

**Issue by jobvk** [jobvk/Home-Assistant-Windcentrale#26]
I received an email on June 28, 2022 at 09:15:04 CEST

That the app and the associated APIs will cease to exist from June 30th. This will mean that this plugin can no longer retrieve data.

I am working on updating the plugin with data from the [new platform](https://mijn.windcentrale.nl/). But that won't be done before June 30.
The new platform uses [AWS](https://aws.amazon.com/). And the API's use now a bearer token for authorization, where they had no authorization in the past.

But I'm working on it if you have any questions in between, feel free to ask me below or via [Discord](https://discordapp.com/users/311908841459810316/). Version 0.2.0 will then be a working version with the new platform.

Email:
![image](https://user-images.githubusercontent.com/32730202/176194575-801e8d95-8070-4934-9814-cd6a79207a78.png)

**Comment by Simanias** [comment]
To bad they change everything, I’m very happy with the integration. If there’s anything I can help with please let me know.

**Comment by gerard76** [comment]
There is an open API as discussed here https://steenderen.net/blog/winddelen-opbrengst-in-home-assistant/

**Comment by jobvk** [comment]
@gerard76 I am currently already using the API discussed there for this custom component. 
But according to the company `De Windcentrale`, this API will stop shortly.
That's why I'm in the process of converting this custom component to the new platform that uses the AWS platform with bearer tokens.

**Comment by gerard76** [comment]
> @gerard76 I am currently already using the API discussed there for this custom component.
> But according to the company `De Windcentrale`, this API will stop shortly.
> That's why I'm in the process of converting this custom component to the new platform that uses the AWS platform with bearer tokens.

Ah ok, sorry, could have seen that. Thanks for putting your time and effort in it.

**Comment by jobvk** [comment]
@Simanias Yeah the app stort working for me. But the API's all seem to work just fine. 
I will continue developing with a new version because I don't know how long these API's will work.

**Comment by Simanias** [comment]
The API just stopped working 2 hours ago. Waiting for your new integration for now.

**Comment by gerard76** [comment]
> The API just stopped working 2 hours ago. Waiting for your new integration for now.

Works for me? [https://zep-api.windcentrale.nl/production/201/live](https://zep-api.windcentrale.nl/production/201/live)

**Comment by jobvk** [comment]
For some odd reason, the old APIs are working again. Unfortunately, I couldn't finish it this week. Next two weeks I will be on vacation and after that I will continue with updating the custom component.

**Comment by jobvk** [comment]
## Time for a update on how it's going

### Credentials API
The API is working. Unfortunately, the token only works for 60 minutes. Therefore, the custom component requests a new token every 55 minutes.

### Live API
The API is working.
The sensor `Run Percentage` is no longer there.
The sensor `Max Power` is renamed to `Power Percentage`.
The sensor `kWh` is renamed to `Production This Year`.
The sensor `Hours Run Total` is add it will show how many hours the windturbine has been running in total.

### Production History API
I haven't started this yet because I'm not quite sure how I'm going to do this yet.

There are many APIs. For example, if you look at the chart for years, you will see 3 years. With a graph for the total windturbine and one for your wind shares. These are all 2 API's, if you then want to add 3 more years, it will become 4 API's.

And that was just the years. If I add months, weeks, days and hours. Then it adds up very quickly.

I'm currently talking to @balk77 about a possible HACS Lovelace card that might have a filter and buttons on it, so you can go through it just like on the website without having to load everything at once.

If anyone else has an idea how this can be done more efficiently, I'd like to hear your suggestion.

### Notifications API
The API is working, only waiting for some more notifications, so I can make sure the filter works again.

### Energy Management
The production sensor that is currently used `sensor.name_day_production` no longer works because the API only updates after the day has already passed. So I created a new sensor and called it `Energy Management`.
The `Energy Management` sensor copy's the value of the `Production This Year` sensor and divides it by total shares and multiply it by the number of shares you own.

Example:
`1.957.764` kWh / `5721` * `9` = `3.079,86575773466` kWh

I'm currently testing to see if it matches the charts from the website.

### Ideas
If anyone else an idea on something that's missing or a new feature. I'd like to hear your suggestion.

**Comment by vressel** [comment]
It seems that the API is no longer delivering actual data, timestamp is stuck on:
"timestamp":"2022-08-01T13:13:30"

**Comment by Hel1Pink** [comment]
@jobvk: I did use de old wincentrale api (zep-api) with and without domoticz. But is did stop workin at 1-8-2022. 
I did find some API-links to de live production, but I am not Authorized. How do I get a token? 
And how can i get te new api to work?

**Comment by jobvk** [comment]
@Hel1Pink I’m still testing. You can expect a release next week. For the live data en the news data. Production history will follow later.

**Comment by Xorfor** [comment]
If possible, I want to be a beta tester?

**Comment by jobvk** [comment]
@Simanias @gerard76 @Xorfor @vressel @Hel1Pink 
If you want you can test the new beta. 
See if everything works well. It's not perfect yet, but I want to see if the live sensors are working. 
The history and news sensors will come back later. 
If something goes wrong or something is not right like missing shares or windturbines, please let us know.
https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.2.0-Beta

**Comment by Xorfor** [comment]
I just installed the new beta. As far as I can check, the data is correct for at least one windmill. Because of no wind, the other windmill doesn't give data.
It is stupid, that they don't make the kWh available per hour or live per day 😢. But I really like to have that data to calculate my total energy consumption/production per day. Even if it is one day too late 😄 .

**Comment by gerard76** [comment]
Works like a charm!

It gave unique names to sensors I already had. All values seem to check out.

I am not sure .energy_management is a good name for my share production. I would have picked:

- sensor.[name]_production
- sensor.[name]_power

over

- sensor.[name]
- sensor.[name]_energy_management

but other then that I am very happy to get everything up and running again! Thanks!

**Comment by vressel** [comment]
Thanks!
Beta now running for several hours, and looking fine, only Last Update gives a message: invalid timestamp.

**Comment by Hel1Pink** [comment]
Thanks. 
It is running from yesterdag evening. Is working fine and de data seems OK for my windmill parts

**Comment by Xorfor** [comment]
I have shares of 2 windmills, De Grote Geert and De Trouwe Wachter. Is there a reason why the data of sensor.de_grote_geert is updated every 30 seconds, but sensor.de_trouwe_wachter only every 10 minutes?

**Comment by rob-on-git** [comment]
Het rode hert looks fine with the beta version.
Still trying to mimic the data I had before when is used the old API.

Keep up the good work!

**Comment by rob-on-git** [comment]
Made a template sensor to mimic the run-percentage for this year:
`{{ (states('sensor.het_rode_hert_hours_run_this_year') | float / (((as_timestamp(now()) - as_timestamp(now().year ~ "-01-01")) / 3600) | round(1)) * 100 )| round(2)}}
`
Might be useful

**Comment by steenderen** [comment]
Hi, just installed it for the replacement of my scripts you guys found at  https://steenderen.net/blog/winddelen-opbrengst-in-home-assistant/ which is indeed also not working anymore. Everything seems to work fine in the beta version. Is there a difference between the Energy Management sensor and the Production This Year?

**Comment by gerard76** [comment]
> Is there a difference between the Energy Management sensor and the Production This Year?

Energy Management is your production (total / total_shares * your shares) and Production this Year is total for the mill.

**Comment by balk77** [comment]
also running fine for me. And I managed to make some graphs:
<img width="1009" alt="Screenshot 2022-08-20 at 21 06 27" src="https://user-images.githubusercontent.com/10166350/185762708-7208a300-0f00-4dc1-9cd8-7c84d6294eaa.png">
It consumes the cumulative yearly kWh production into a [Utility Meter](https://www.home-assistant.io/integrations/utility_meter/) sensor, into a hourly, daily, weekly and monthly buckets. It then takes the data from the long term statistics database and plots with Apexcharts. Explained here:

**Comment by Xorfor** [comment]
Hmmm. Today no data from De Grote Geert:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/windcentrale/sensor.py", line 158, in update
    self._state = self._windturbine.live_data[self._sensor]
KeyError: 'wind_power'

**Comment by Xorfor** [comment]
For some reason I get data again from De Grote Geert since last night. I guess this windmill didn't deliver data (again) yesterday.

**Comment by jobvk** [comment]
> Made a template sensor to mimic the run-percentage for this year: `{{ (states('sensor.het_rode_hert_hours_run_this_year') | float / ((as_timestamp(now()) - as_timestamp(now().year ~ "-01-01")) / 3600) * 100 )| round(2)}} ` Might be useful

@rob-on-git I added your formula to version [0.2.1](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.2.1)

**Comment by rob-on-git** [comment]
> ### Energy Management
> 
> The production sensor that is currently used `sensor.name_day_production` no longer works because the API only updates after the day has already passed. So I created a new sensor and called it `Energy Management`. The `Energy Management` sensor copy's the value of the `Production This Year` sensor and divides it by total shares and multiply it by the number of shares you own.
> 
> Example: `1.957.764` kWh / `5721` * `9` = `3.079,86575773466` kWh
> 
> I'm currently testing to see if it matches the charts from the website.
> ### Ideas
> 
> If anyone else an idea on something that's missing or a new feature. I'd like to hear your suggestion.

Hi Job, 

The energy-management works fine, but i would suggest you do a 'round(3)' on it, as a Wh is already detailed, and more digits is a bit useless, i would say.

Also, I would suggest you rename it to : <mill>_energy_shares
(and optional, the <mill>_production_this_year to <mill>_energy)

**Comment by Xorfor** [comment]
Thanks to the ideas from @balk77 I get almost the same values per day as in the windcentrale portal
![](https://user-images.githubusercontent.com/32778657/186227878-1311b5d1-03de-4e7c-9821-f5401890d0ae.png).

**Comment by Hel1Pink** [comment]
@jobvk 
I want to thank you for the good work. I do not use Home Assistant, but your scripts helped me to access the new windcentrale PI.  I made my own python script to put data of Livewind and History directly in a MariaDB database. I use Grafana to visualize the grafics.

**Comment by balk77** [comment]
I have noticed a weird irregularity earlier this week. The sensor reported **minus** 17 **thousand** kWh production. Next datapoint it was corrected again. This offsets the utility meter sensor quite a bit.

Did anyone else experience this? Would it be possible to build in a filter to remove these big jumps? I did not find this spike on mijn windcentrale.

![Screenshot_20220825-184617](https://user-images.githubusercontent.com/10166350/186723323-34f0dea3-0f07-4204-a8ff-e3900615afce.png)

**Comment by rob-on-git** [comment]
Maybe another usefull item. Some people want to know how much production is already realized in %.
(ofcourse, you can see it through the graphs, but a percentage is easier to read.

I've got this template inserted:
```
    [windmill]_produced_this_year:
      friendly_name: [Windmill] Year production prognoses
      unit_of_measurement: '%'
      value_template: >
        {{ (states('sensor.[windmill]_production_this_year') | float / 3324000 * 100 ) | round(1) 
}}
```

Where the value is the total amount of shares from a windmill * 500 (500kW ~ one share)

It is not totally accurate, cause not every windmill has 500kW/share, but it is close enough i think. And within your code I did see already the amount of shares defined for every windmill.

**Comment by rob-on-git** [comment]
> I have noticed a weird irregularity earlier this week. The sensor reported **minus** 17 **thousand** kWh production. Next datapoint it was corrected again. This offsets the utility meter sensor quite a bit.
> 
> Did anyone else experience this? Would it be possible to build in a filter to remove these big jumps? I did not find this spike on mijn windcentrale.
> 
> ![Screenshot_20220825-184617](https://user-images.githubusercontent.com/10166350/186723323-34f0dea3-0f07-4204-a8ff-e3900615afce.png)
> 
> Edit: There was a peak but not that large: ![Screenshot_20220825-185547](https://user-images.githubusercontent.com/10166350/186725993-9892743e-e0d8-4190-a88e-6121e4f2960c.png)

To avoid those spikes, i usually make an extra sensor with something like this:
```
[windmill]_prod:
 value_template: >-
          {% if float([windmill]_production) > 100000 %}
            unknown
          {% else %}
            {{ [windmill]_production }}
          {% endif %}
```

Where, ofcourse the 10000 is the max value you think should be allowed...

**Comment by balk77** [comment]
> value_template: >-
>           {% if float([windmill]_production) > 100000 %}
>             unknown
>           {% else %}
>             {{ [windmill]_production }}
>           {% endif %}

Thanks for the suggestion! You have put me on the right track; I have configured a [`filter` sensor](https://www.home-assistant.io/integrations/filter/) instead. Advantage: easier to configure and it passes the old value if filter was activated.
```
- platform: filter
  name: "het rode hert energy management filtered"
  entity_id: sensor.het_rode_hert_energy_management
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
      precision: 3
```
My maximum daily production is approximately 6.5 kWh. A jump of 4 kWh would indicate an outlier.

**Comment by rob-on-git** [comment]
> Suggestion: add the total number and the number of owned shares of a windmill as entities. This allows us to do calculations without 'hardcoded' values.

The amount of shares is already there, as attribute of the windmill entitity. This can already be used for calculation.
The total amount is not there (i believe, not available through API, hence harcoded, but maybe job can export those from hardcoded to the attribute).

**Comment by jobvk** [comment]
> > ### Energy Management
> > The production sensor that is currently used `sensor.name_day_production` no longer works because the API only updates after the day has already passed. So I created a new sensor and called it `Energy Management`. The `Energy Management` sensor copy's the value of the `Production This Year` sensor and divides it by total shares and multiply it by the number of shares you own.
> > Example: `1.957.764` kWh / `5721` * `9` = `3.079,86575773466` kWh
> > I'm currently testing to see if it matches the charts from the website.
> > ### Ideas
> > If anyone else an idea on something that's missing or a new feature. I'd like to hear your suggestion.
> 
> Hi Job,
> 
> The energy-management works fine, but i would suggest you do a 'round(3)' on it, as a Wh is already detailed, and more digits is a bit useless, i would say.
> 
> Also, I would suggest you rename it to : [mill]_energy_shares (and optional, the [mill]_production_this_year to [mill]_energy)

Name changes will be available in version 0.2.2

**Comment by jobvk** [comment]
> mber and the number of owned shares of a windmill as entities. This allows us to do cal

I created a discussions page where you van share your ideas
https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/ideas

**Comment by jobvk** [comment]
> > I have noticed a weird irregularity earlier this week. The sensor reported **minus** 17 **thousand** kWh production. Next datapoint it was corrected again. This offsets the utility meter sensor quite a bit.
> > Did anyone else experience this? Would it be possible to build in a filter to remove these big jumps? I did not find this spike on mijn windcentrale.
> > Edit: There was a peak but not that large:
> 
> To avoid those spikes, i usually make an extra sensor with something like this:
> 
> ```
> [windmill]_prod:
>  value_template: >-
>           {% if float([windmill]_production) > 100000 %}
>             unknown
>           {% else %}
>             {{ [windmill]_production }}
>           {% endif %}
> ```
> 
> Where, ofcourse the 10000 is the max value you think should be allowed...
@rob-on-git 
I'm looking in to it. maybe you added it to the discussions page where you van share your ideas.
https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/ideas

**Comment by jobvk** [comment]
### Many thanks to everyone who helped fixing this issue

I am closing this issue now as the original issue has been resolved for the majority. If you want to talk about the wind power plant in general, be sure to check out the github discussions general page.
https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/general

If you have any ideas that should be added, please post them on the github discussions ideas page.
https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/ideas
