### ISSUE TITLE
Run percentage and hours run, show large negative values.

### ISSUE THREAD

**Issue by Simanias** [jobvk/Home-Assistant-Windcentrale#37]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

In the latest version 0.2.1 the new values of 'run percentage' and 'hours run' show a large negative value.
I have tried to reset the values by removing the integration and re-install it, but no joy.

<img width="310" alt="Schermafbeelding 2022-08-30 om 11 53 44" src="https://user-images.githubusercontent.com/4976061/187408479-d3f57de9-53ac-4ce7-97e7-46eb9bd0706b.png">

### What is version of Home Assistant Core did you recieve the bug?

8.4

### What is version of Home Assistant Supervisor did you recieve the bug?

2022.08.5

### What is version of Home Assistant Supervisor?

2022.08.7

### What is version of the Windcentrale integration?

0.2.1

**Comment by jobvk** [comment]
@Simanias Thx you for making this issue.

I looked at the API that provided this information and it contains the wrong data.

The API does indeed return large negative values. That is indeed what you see in the sensor `hours run this year`. And the sensor `run percentage` is calculated on that so that's why it also shows wrong data.

Unfortunately I can't do much about this at the moment. But I will send an email to the developers of the official website and ask if they can solve this.

**Comment by balk77** [comment]
We have seen other large jumps as well. Would it make sense to add a filter in this integration on sensors where we know it cannot happen? Can a custom integration make use of built-in integrations like [`filter`](https://www.home-assistant.io/integrations/filter/)?

**Comment by jobvk** [comment]
Is it still happening?

**Comment by Simanias** [comment]
> Is it still happening?

You mean with the new version 0.2.4? 
For me their are still 2 very large negative values.

**Comment by balk77** [comment]
For me the last one was on 12 Sept.

**Comment by jobvk** [comment]
@Simanias The data given by the Live API is still wrong. But since this data is not shown on the official site. I don't think they are going to fix it.

``` json
{
   "WND-BH":{
      "id":"111",
      "timestamp":"1665169810",
      "wind_power":"7",
      "power":"849",
      "wind_direction":"ZW",
      "year_production":"1809880",
      "rpm":"26.1",
      "total_runtime":"113006",
      "year_runtime":"-383872785.244444",
      "diameter":"100",
      "pulsating":"1",
      "power_percentage":"100",
      "power_per_share":"153"
   }
}
```

**Comment by Simanias** [comment]
Maybe we should close the issue, since there is nothing you can do to resolve the wrong data from the API.

**Comment by balk77** [comment]
> Maybe we should close the issue, since there is nothing you can do to resolve the wrong data from the API.

We could still create a filter as part of the integration? I have this:
```
- platform: filter
  name: "het rode hert energy management filtered"
  entity_id: sensor.het_rode_hert_energy_shares
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
      precision: 3
```
How difficult is it to apply this by default?

**Comment by jobvk** [comment]
@Simanias I send an email again and the reaction of the customer service was:
`We cannot solve this problem for you as it is not our software and code.`

@balk77 I don't think you should change the data but you can do it for your self
