### ISSUE TITLE
Total number of shares is incorrect when you have several participations for a windturbine

### ISSUE THREAD

**Issue by gh471** [jobvk/Home-Assistant-Windcentrale#53]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

The total number of shares is incorrect when you have several participations for a windturbine. 
I had already a participation with 3 shares for windturbine TW (Trouwe Wachter) and bought an extra participation with 1 share (also TW).
The problem is that integration still shows only information on 3 shares. (sensor.de_trouwe_wachter and sensor.de_trouwe_wachter_power_per_share)

![image](https://user-images.githubusercontent.com/5664692/195826421-4ddb3258-006c-4de8-9974-1355931deca8.png)

### What is version of Home Assistant Core did you recieve the bug?

2022.10.2

### What is version of Home Assistant Supervisor did you recieve the bug?

2022.10.0

### What is version of Home Assistant Supervisor?

9.0

### What is version of the Windcentrale integration?

0.2.4

### Anything in the logs that might be useful for us?

2022-10-10 22:44:47.398 INFO (MainThread) [custom_components.windcentrale.wind] Testing if user credentails are correct
2022-10-10 22:44:47.398 INFO (MainThread) [custom_components.windcentrale.wind] Updating live data of windturbine De Trouwe Wachter using Rest API
2022-10-10 22:44:47.399 INFO (MainThread) [custom_components.windcentrale.wind] Updating news data sensor
2022-10-10 22:44:57.430 INFO (MainThread) [custom_components.windcentrale.wind] Updating live data of windturbine De Trouwe Wachter using Rest API

### Additional information

I did some research on the issue and hope it helps a little...

1. The json message contains the correct informatie:
![image](https://user-images.githubusercontent.com/5664692/195827808-83fcd765-5da9-4a21-8b49-4a53ba5db20c.png)
2. The code already contains a method to collect all the shares: `class Credentials: async def collect_projects_windshares(self):` but is not called (the info text does appear in logs)

**Comment by jobvk** [comment]
I'll look in to it, could you send me the JSON message to my email: [developer@jobvankoeveringe.com](mailto:developer@jobvankoeveringe.com)
Please change any private data to `null`

**Comment by jobvk** [comment]
Issue is solved by step 4-5-6
