### ISSUE TITLE
Error retrieving data

### ISSUE THREAD

**Issue by abko** [jobvk/Home-Assistant-Windcentrale#61]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

Since Nov 14 16:00 ish these errors appeared, while data is available through the mijn Windcentrale pages. 

### What is version of Home Assistant Core did you recieve the bug?

2022.11.1

### What is version of Home Assistant Supervisor did you recieve the bug?

Frontend 20221102.1 - latest

### What is version of Home Assistant Supervisor?

Frontend 20221102.1 - latest

### What is version of the Windcentrale integration?

Latest

### Anything in the logs that might be useful for us?

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/windcentrale/sensor.py:158 
Integration: Windcentrale (documentation, issues) 
First occurred: 14 November 2022 at 15:57:20 (2927 occurrences) 
Last logged: 16:20:23

Update for sensor.de_jonge_held fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/windcentrale/sensor.py", line 158, in update
    self._state = self._windturbine.live_data[self._sensor] * self._windturbine.shares
KeyError: 'power_per_share'

**Comment by sebastianberm** [comment]
This is not restricted to 1 windturbine, but it seems like it's all of them.
At the moment, I have 5 different turbines giving back these errors, so I think it's something that was changed on the API?

**Comment by QNimbus** [comment]
> This is not restricted to 1 windturbine, but it seems like it's all of them. At the moment, I have 5 different turbines giving back these errors, so I think it's something that was changed on the API?

I have the same issue but haven't had time to investigate yet - it might be related to the JWT session expiring prematurely?

**Comment by jobvk** [comment]
I also had this problem. But after restarting home assistant once, the problem did not reappear. I will leave this issue open for a while in case it occurs more often.

**Comment by abko** [comment]
Thanks Job. I did not try restarting HA earlier. Indeed the problem seems to have recovered. If I will encounter it again I will report it here.

**Comment by krispijnb** [comment]
I've had the same issue from November 11th till November 13th. Yesterday it occured again around 16:00hrs. Restarting HA as described above seems to have solved the issue time.

**Comment by sebastianberm** [comment]
The restart indeed seems to fix the issue. I don't know where this plugin stores the JWT session data, so the idea of a session expiring prematurely does seem to make sense.

**Comment by Xorfor** [comment]
I also had this problem. On 14th november @ 16:00 the last data for both windmills. Restarting HA is works again.
I also had problems to get data on the windcentrale.nl website.

**Comment by Xorfor** [comment]
Today since 5:55 no data received. After restart of the HA, data is displayed gain.

**Comment by sebastianberm** [comment]
It seems like the JWT expires ahead of time or responds in a strange way. I am not 100% sure how the tokens are stored in HA, so I can't be sure.

In my case, it seems like a restart of HA fixes it in 100% of the cases, but turning something off and on again isn't a fix ;-).
So I would suggest a mechanism to check the JWT and reauthenticate if it does expire ahead of time (or at least a way to deal with it).

**Comment by jobvk** [comment]
I am not quite sure myself where the problem lies. I got several errors in a short time:

- Invalid response from server for collection live data of windturbine De Witte Juffer the response data and code 401
- Invalid response from server for collection live data of windturbine De Witte Juffer the response data `<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> </body> </html>` and code 502
- Invalid response from server for collection live data of windturbine De Witte Juffer the response data `<html> <head><title>503 Service Temporarily Unavailable</title></head> <body> <center><h1>503 Service Temporarily Unavailable</h1></center> </body> </html>` and code 503

**Comment by abko** [comment]
@jobvk Could it be that the problem occurs when there is a period with 0 production? Looking at the data in HA seems to suggest that, but I might be wrong.

**Comment by johan-de-jong** [comment]
From 2022-11-28 22:21:27h until about 2022-11-30 15:05h /config/home-assistant.log is filled with errors.
<pre>
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_wind_speed fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_wind_direction fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_run_percentage fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_revolutions_per_minute fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_power_total fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_power_percentage fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_power_per_share fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_last_update fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_hours_run_total fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_hours_run_this_year fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_energy_shares fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_energy_prognoses_this_year fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer_energy fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_witte_juffer fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_wind_speed fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_wind_direction fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_run_percentage fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_revolutions_per_minute fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_power_total fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_power_percentage fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_power_per_share fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_last_update fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_hours_run_total fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_hours_run_this_year fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_energy_shares fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_energy_prognoses_this_year fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert_energy fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.de_grote_geert fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.de_witte_juffer_pulsating fails
   4907 x ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.de_grote_geert_pulsating fails
     16 x ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Grote Geert the response data <html>
     15 x ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Witte Juffer the response data <html>
     11 x ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Witte Juffer the response data  and code 401
     10 x ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Grote Geert the response data  and code 401
      4 x ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection news data
      1 x WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration windcentrale which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
      1 x ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Witte Juffer the response data <!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html> and code 500
      1 x ERROR (MainThread) [custom_components.windcentrale.wind] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='mijn.windcentrale.nl', port=443): Max retries exceeded with url: /api/v0/sustainable/notices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5aaccc70>: Failed to establish a new connection: [Errno -3] Try again'))"))
      1 x ERROR (MainThread) [custom_components.windcentrale.wind] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='mijn.windcentrale.nl', port=443): Max retries exceeded with url: /api/v0/sustainable/notices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ee0babee0>: Failed to establish a new connection: [Errno -3] Try again'))"))
      1 x ERROR (MainThread) [custom_components.windcentrale.wind] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='mijn.windcentrale.nl', port=443): Max retries exceeded with url: /api/v0/sustainable/notices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ee0b92080>: Failed to establish a new connection: [Errno -3] Try again'))"))
      1 x ERROR (MainThread) [custom_components.windcentrale.wind] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='mijn.windcentrale.nl', port=443): Max retries exceeded with url: /api/v0/sustainable/notices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ee0a6ece0>: Failed to establish a new connection: [Errno -3] Try again'))"))
   </pre>

**Comment by jobvk** [comment]
For everyone who had this problem, please check if you still have this problem after updating to version [0.2.6](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.2.6)

**Comment by jobvk** [comment]
Is this problem still relevant or can it be closed?

**Comment by sebastianberm** [comment]
I've had issues, but they were related to Windcentrale providing incorrect data. So I think this can be closed 👍 .

Thanks!

**Comment by abko** [comment]
@jobvk Since the update it has also not surfaced for me anymore. I believe it can be closed.
