### ISSUE TITLE
Unexpected high sensor.de_jonge_held_energy_shares value

### ISSUE THREAD

**Issue by abko** [jobvk/Home-Assistant-Windcentrale#73]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

Sometimes I experience a very high value for this property, leading to the Energy dashboard showing a huge peak of production, while this did not happen.

It happened just today, while windcentrale is even having an error, reporting no energy production.

It can be fixed by adjusting the statistics via developer tools (note I screwed up making screenshots before fixing it, so this is a manual adjustment to show the same).

<img width="463" alt="image" src="https://user-images.githubusercontent.com/360683/211824423-699db5b1-12e8-4fc8-b1dc-132148b2b4e4.png">

I am not sure if it's related to this log entry:
`Logger: homeassistant.components.sensor
Source: custom_components/windcentrale/sensor.py:235 
Integration: Sensor (documentation, issues) 
First occurred: 13:56:40 (2 occurrences) 
Last logged: 13:56:40

Error adding entities for domain sensor with platform windcentrale
Error while setting up windcentrale platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/windcentrale/sensor.py", line 235, in async_added_to_hass
    self.attr[week] = state.attributes[week]
KeyError: 'Week 0'
`

### What is version of Home Assistant Core did you recieve the bug?

Home Assistant 2022.12.8 Frontend 20221213.1 - latest

### What is version of Home Assistant Supervisor did you recieve the bug?

Home Assistant 2022.12.8 Frontend 20221213.1 - latest

### What is version of Home Assistant Supervisor?

Home Assistant 2022.12.8 Frontend 20221213.1 - latest

### What is version of the Windcentrale integration?

0.2.6

### Anything in the logs that might be useful for us?

Logger: homeassistant.components.sensor
Source: custom_components/windcentrale/sensor.py:235 
Integration: Sensor (documentation, issues) 
First occurred: 13:56:40 (2 occurrences) 
Last logged: 13:56:40

Error adding entities for domain sensor with platform windcentrale
Error while setting up windcentrale platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/windcentrale/sensor.py", line 235, in async_added_to_hass
    self.attr[week] = state.attributes[week]
KeyError: 'Week 0'

### Additional information

I have seen it in total 3-4 times since I run the integration (about 2 months)

**Comment by jobvk** [comment]
Let me know if you still have the problem after today

**Comment by abko** [comment]
I have not since it since the API started working again. Will post it here when it happens again.

**Comment by jobvk** [comment]
If you want to fix your energy dashboard I removed _statistics_ from the database to fix this problem.
I made some instructions https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/76
