### ISSUE TITLE
Energy Shares Rode Hert not visible

### ISSUE THREAD

**Issue by mschut** [jobvk/Home-Assistant-Windcentrale#94]
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

Within the Windcentrale integration we are using the shares of three windmills. However, only the value of Energy Shares of the Rode Hert remains 0,0kWh. The other two mills do show their values. Within the Rode Hert values, it does show the value (Watt) per share, and the total value for our shares for this mill. The issue therefore is that there is a sync of the values for the Rode Hert, only not in the value which is used in the Energy view. 

![Schermafbeelding 2023-03-07 om 19 59 54](https://user-images.githubusercontent.com/11066663/223524307-8376f9d5-1b68-4d7d-8a8a-12b834df575c.png)

### What is version of Home Assistant Core did you receive the bug?

Home Assistant 2023.3.1

### What is version of Home Assistant Supervisor did you receive the bug?

Supervisor 2023.01.1

### What is version of Home Assistant Supervisor?

Operating System 9.5

### What is version of the Windcentrale integration?

0.2.6

**Comment by jobvk** [comment]
Check https://github.com/jobvk/Home-Assistant-Windcentrale/issues/72

You have to contact the company with and ask if they can fix it. You can use this json:

Rode Hert
``` json
{
   "WND-RH":{
      "diameter":"32",
      "year_runtime":"0",
      "total_runtime":"0",
      "rpm":"13.4",
      "year_production":"0",
      "wind_direction":"ZO",
      "power":"392",
      "wind_power":"4",
      "timestamp":"1676451130",
      "id":"31",
      "power_per_share":"59",
      "power_percentage":"20",
      "pulsating":"0"
   }
}
```
